azs:
- name: z1

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 6

disk_types:
- name: default
  disk_size: 0

networks:
- name: default
  type: manual
  subnets:
  - azs: [z1]
    dns: [192.168.65.1]
    range: 10.0.0.0/16
    gateway: 10.0.0.1
    reserved: [10.0.0.4]

vm_types:
- name: default