azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: minimal
  workers: 6
disk_types:
- disk_size: 1024
  name: 1GB
- disk_size: 5120
  name: 5GB
- disk_size: 10240
  name: 10GB
- disk_size: 100240
  name: 100GB
# Note: the "default" disk type is not used in cf-deployment.
# it is included for compatibility with the bosh-deployment
# cloud-config.
- disk_size: 1024
  name: default
networks:
- name: default
  type: manual
  subnets:
  - azs: [z1, z2, z3]
    dns: [192.168.65.1]
    range: 10.0.0.0/16
    gateway: 10.0.0.1
    reserved: [10.0.0.4]
    static: [((static_ip))]

vm_extensions:
- name: 5GB_ephemeral_disk
- name: 10GB_ephemeral_disk
- name: 50GB_ephemeral_disk
- name: 100GB_ephemeral_disk
- name: 500GB_ephemeral_disk
- name: 1TB_ephemeral_disk
- name: ssh-proxy-and-router-lb
  cloud_properties:
    ports:
    - host: 80
    - host: 443
    - host: 2222
- name: cf-tcp-router-network-properties
  cloud_properties:
    ports:
    - host: 1024-1123
- name: credhub-lb
  cloud_properties:
    ports:
    - host: 8845
vm_types:
- name: minimal
- name: small
- name: small-highmem
# Note: the "default" vm type is not used in cf-deployment.
# it is included for compatibility with the bosh-deployment
# cloud-config.
- name: default
