kernel:
  image: linuxkit/kernel:4.14.70
  cmdline: "console=ttyS0 page_poison=1"
init:
  - linuxkit/vpnkit-expose-port:v0.6
  - linuxkit/init:v0.6
  - linuxkit/runc:v0.6
  - linuxkit/containerd:v0.6
  - linuxkit/ca-certificates:v0.6
  - linuxkit/getty:v0.6
  - aemengo/runc-cpid:e37a1df29987e4e8b8adfb2c810c4a7c390f50e6-amd64
onboot:
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib"]
  - name: swap
    image: linuxkit/swap:v0.6
    command: ["/swap.sh", "--path", "/var/lib/swap", "--size", "1024M"]
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: mount-vpnkit
    image: alpine:3.8
    binds:
      - /var/:/host_var:rbind,rshared
    capabilities:
      - CAP_SYS_ADMIN
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir /host_var/vpnkit && mount -v -t 9p -o trans=virtio,dfltuid=1001,dfltgid=50,version=9p2000 port /host_var/vpnkit"]
services:
  - name: acpid
    image: linuxkit/acpid:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: host-timesync-daemon
    image: linuxkit/host-timesync-daemon:613dc55e67470ec375335a1958650c3711dc4aa6
  - name: vpnkit-forwarder
    image: linuxkit/vpnkit-forwarder:v0.6
    binds:
      - /var/vpnkit:/port
    net: host
    command: ["/vpnkit-forwarder"]
  - name: vpnkit-manager
    image: aemengo/vpnkit-manager:84fc0f59abc57cd5256cc0541763d78895b371ba-amd64
    net: host
    capabilities:
      - all
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port # userland proxy
      - /var/vpnkit:/port                                       # vpnkit control 9p mount
      - /var/run:/var/run
    command: ["/usr/bin/vpnkit-manager",
              "--expose", "10.0.0.4:25555:10.0.0.4:25555",
              "--expose", "10.0.0.4:6868:10.0.0.4:6868",
              "--expose", "10.0.0.4:22:10.0.0.4:22"]
trust:
  org:
    - linuxkit